""" add field amount in table payment_accounts

Revision ID: 8a5bc8407b08
Revises: 4cd231d356fa
Create Date: 2026-02-14 19:55:30.876291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5bc8407b08'
down_revision: Union[str, Sequence[str], None] = '4cd231d356fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_accounts', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_accounts', 'amount')
    # ### end Alembic commands ###
